### ISSUE TITLE
Travis x86 is no more working

### ISSUE THREAD

**Issue by hannesa2** [mmcc007/test_emulators#5]
x86 stops working.
I tested it on my [fork](https://travis-ci.org/hannesa2/test_emulators/builds/620483302) and when  you retrigger your last [build](https://travis-ci.org/mmcc007/test_emulators/builds/610596318) , I expect the same non-working result

But I guess, you already know it https://travis-ci.community/t/add-kvm-support/1406/13

**Comment by mmcc007** [comment]
Seems like it might be an infrastructure issue (since an equivalent build still runs on [cirrus](https://cirrus-ci.com/build/6037328228777984)). So hopefully travis will fix it. Acceleration is still [enabled](https://travis-ci.com/mmcc007/default_flutter_app/jobs/263196607#L203), so it might be a library issue.

**Comment by mmcc007** [comment]
Pinned emulator is [working](https://travis-ci.org/mmcc007/test_emulators/jobs/621310460#L247).

**Comment by hannesa2** [comment]
https://raw.githubusercontent.com/DanySK/Gravis-CI/master/ is solved and shipped, but Travis still doesn't work. It's using `29.3.0.0` now

On my fork, based on your master, x86 isn't working with `29.3.0.0` at all https://travis-ci.org/hannesa2/test_emulators/builds/620483302

My expectation was, simply use  `29.3.0.0` and it's working again
Is there an additional step needed ?

**Comment by mmcc007** [comment]
Unpinned x86 emulator (29.2.1.0 ==> 29.3.0). Version 29.3.1 is making it's way out soon.
Pinning should no longer be necessary: https://issuetracker.google.com/issues/145622251
Fixed in version 29.3.1 https://androidstudio.googleblog.com/2019/12/emulator-2930-stable.html
Also upgraded flutter version and migrated flutter app to androidX (required for new flutter version)
(Note: fix applied on dev branch)
https://travis-ci.org/mmcc007/test_emulators/builds/624531206
(not all tests are passing, but probably unrelated to this issue)
